# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-cloudwatch-events
  description: Terraform Module for provisioning CloudWatch Events rules connected with targets.
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-module, cloudwatch, cloudwatch-events, aws, hcl2

